name: Deploy API to Azure App Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'timesheet-api-prod'  # Azure App Service名
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
        package: '.'
